name: Build and Push Custom Bluefin Image

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build-and-push:
    runs-on: ubuntu-latest 

    permissions:
      contents: read 
      packages: write 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Custom Bluefin Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true 
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
          platforms: linux/amd64
          cache-from: type=gha 
          cache-to: type=gha,mode=max 
